# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WRTPluginLite
                                 A QGIS plugin
 Description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-04
        copyright            : (C) 2026 by Muhammad Ahmad
        email                : mahmada2904@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WRTPluginLite class from file WRTPluginLite.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wrt_plugin_lite import WRTPluginLite
    return WRTPluginLite(iface)
