# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WRTPluginLite
                                 A QGIS plugin
 Description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Muhammad Ahmad
        email                : mahmada2904@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .resources import *
from .wrt_plugin_lite_dialog import WRTPluginLiteDialog
from .vis_panel_dialog import VisPanelDialog
import os.path


class WRTPluginLite:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WRTPluginLite_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&WRT Plugin Lite')
        self.first_start = None
        self.first_start_vis = None

    def tr(self, message):
        return QCoreApplication.translate('WRTPluginLite', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/wrt_plugin_lite/icon.png'

        # Button 1 — Configuration Wizard
        self.add_action(
            icon_path,
            text=self.tr(u'WRT Config Wizard'),
            callback=self.run,
            status_tip='Open WRT configuration wizard',
            parent=self.iface.mainWindow()
        )

        # Button 2 — Visualisation Panel
        self.add_action(
            icon_path,
            text=self.tr(u'WRT Visualise'),
            callback=self.run_vis,
            status_tip='Open WRT visualisation panel',
            parent=self.iface.mainWindow()
        )

        self.first_start     = True
        self.first_start_vis = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&WRT Plugin Lite'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Open the configuration wizard."""
        if self.first_start:
            self.first_start = False
            self.dlg = WRTPluginLiteDialog()

        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            pass

    def run_vis(self):
        """Open the standalone visualisation panel."""
        if self.first_start_vis:
            self.first_start_vis = False
            self.vis_dlg = VisPanelDialog()

        self.vis_dlg.show()
        self.vis_dlg.raise_()
        self.vis_dlg.activateWindow()
