# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WRTPluginLiteDialog
                                 A QGIS plugin
 Description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Muhammad Ahmad
        email                : mahmada2904@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QDateTime
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox, QTableWidgetItem
from qgis.utils import iface

from .route_map_tool import RouteMapTool

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "wrt_plugin_lite_dialog_base.ui")
)


class WRTPluginLiteDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(WRTPluginLiteDialog, self).__init__(parent)
        self.setupUi(self)

        self.state = {
            "source": None,
            "destination": None,
            "waypoints": [],
            "departure_time": None,
            "arrival_time": None,
            "forecast_horizon": 90,
            "forecast_resolution": 3,
            "algorithm": "genetic",
            "boat_preset": "Generic Cargo",
            "data_mode": "Automatic",
            "weather_path": "",
            "depth_path": "",
            "route_output_path": "",
        }

        self._prev_map_tool = None
        self._route_tool = RouteMapTool(iface.mapCanvas(), self._on_point_picked)

        self._setup_ui()
        self._connect_signals()
        self._load_defaults()
        self._refresh_route_table()
        self._update_navigation_buttons()
        self._update_summary()

    def _setup_ui(self):
        self.navList.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)

        self.tableRoute.setHorizontalHeaderLabels(["Type", "Latitude", "Longitude"])
        self.tableRoute.verticalHeader().setVisible(False)
        self.tableRoute.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRoute.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableRoute.horizontalHeader().setStretchLastSection(True)

        self.dateTimeDeparture.setDateTime(QDateTime.currentDateTime())
        self.dateTimeArrival.setDateTime(QDateTime.currentDateTime().addSecs(24 * 3600))

    def _connect_signals(self):
        self.navList.currentRowChanged.connect(self._change_page)

        self.btnNext.clicked.connect(self._go_next)
        self.btnBack.clicked.connect(self._go_back)
        self.btnCancel.clicked.connect(self.reject)

        self.btnPickRoute.clicked.connect(self._start_pick_route)
        self.btnClearRoute.clicked.connect(self._clear_route)

        self.comboAlgorithm.currentTextChanged.connect(self._on_algorithm_changed)
        self.comboVessel.currentTextChanged.connect(self._on_vessel_changed)
        self.comboDataMode.currentTextChanged.connect(self._on_data_mode_changed)

        self.dateTimeDeparture.dateTimeChanged.connect(self._on_departure_changed)
        self.dateTimeArrival.dateTimeChanged.connect(self._on_arrival_changed)
        self.spinForecastHorizon.valueChanged.connect(self._on_forecast_horizon_changed)
        self.spinForecastResolution.valueChanged.connect(self._on_forecast_resolution_changed)

        self.lineWeatherPath.textChanged.connect(self._on_weather_path_changed)
        self.lineDepthPath.textChanged.connect(self._on_depth_path_changed)
        self.lineRouteOutputPath.textChanged.connect(self._on_route_output_path_changed)

    def _load_defaults(self):
        self.comboAlgorithm.clear()
        self.comboAlgorithm.addItems([
            "Genetic Algorithm",
            "Isofuel Algorithm",
        ])

        self.comboVessel.clear()
        self.comboVessel.addItems([
            "Generic Cargo",
            "Fast Vessel",
        ])

        self.comboDataMode.clear()
        self.comboDataMode.addItems([
            "Automatic",
            "Manual",
        ])

        self.comboAlgorithm.setCurrentIndex(0)
        self.comboVessel.setCurrentText("Generic Cargo")
        self.comboDataMode.setCurrentText("Automatic")

        self.spinForecastHorizon.setValue(90)
        self.spinForecastResolution.setValue(3)

        self.lineWeatherPath.setText("/path/to/output/weather.nc")
        self.lineDepthPath.setText("/path/to/output/depth.nc")
        self.lineRouteOutputPath.setText("/path/to/output/route.json")

        self.state["departure_time"] = self.dateTimeDeparture.dateTime().toString("yyyy-MM-dd HH:mm")
        self.state["arrival_time"] = self.dateTimeArrival.dateTime().toString("yyyy-MM-dd HH:mm")
        self.state["weather_path"] = self.lineWeatherPath.text()
        self.state["depth_path"] = self.lineDepthPath.text()
        self.state["route_output_path"] = self.lineRouteOutputPath.text()

    def _change_page(self, index):
        if index < 0 or index >= self.stackedWidget.count():
            return
        self.stackedWidget.setCurrentIndex(index)
        self._update_navigation_buttons()
        self._update_summary()

    def _go_next(self):
        current_index = self.stackedWidget.currentIndex()
        last_index = self.stackedWidget.count() - 1

        self._collect_form_data()

        if current_index == last_index:
            self._export_json()
            return

        self.stackedWidget.setCurrentIndex(current_index + 1)
        self.navList.setCurrentRow(current_index + 1)

        if self.stackedWidget.currentIndex() == last_index:
            self._update_summary()

        self._update_navigation_buttons()

    def _go_back(self):
        current = self.stackedWidget.currentIndex()
        if current > 0:
            self.navList.setCurrentRow(current - 1)

    def _update_navigation_buttons(self):
        current = self.stackedWidget.currentIndex()
        last_index = self.stackedWidget.count() - 1

        self.btnBack.setEnabled(current > 0)

        if current == last_index:
            self.btnNext.setText("Finish")
        else:
            self.btnNext.setText("Next")

    def _start_pick_route(self):
        canvas = iface.mapCanvas()
        self._prev_map_tool = canvas.mapTool()
        self._route_tool.reset()
        canvas.setMapTool(self._route_tool)

        QMessageBox.information(
            self,
            "Route Selection",
            "Click once on the map to set SOURCE, then click again to set DESTINATION."
        )

    def _on_point_picked(self, kind, lat, lon):
        if kind == "source":
            self.state["source"] = (lat, lon)
        elif kind == "destination":
            self.state["destination"] = (lat, lon)
            self._restore_previous_map_tool()

        self._refresh_route_table()
        self._update_summary()

    def _restore_previous_map_tool(self):
        canvas = iface.mapCanvas()
        if self._prev_map_tool is not None:
            canvas.setMapTool(self._prev_map_tool)
            self._prev_map_tool = None

    def _clear_route(self):
        self.state["source"] = None
        self.state["destination"] = None
        self.state["waypoints"] = []
        self._refresh_route_table()
        self._restore_previous_map_tool()
        self._update_summary()

    def _refresh_route_table(self):
        rows = []

        if self.state["source"] is not None:
            rows.append(("Source", self.state["source"][0], self.state["source"][1]))

        for i, wp in enumerate(self.state["waypoints"], start=1):
            rows.append((f"Waypoint {i}", wp[0], wp[1]))

        if self.state["destination"] is not None:
            rows.append(("Destination", self.state["destination"][0], self.state["destination"][1]))

        if not rows:
            rows = [
                ("Source", "", ""),
                ("Destination", "", "")
            ]

        self.tableRoute.setRowCount(len(rows))

        for row_idx, row_data in enumerate(rows):
            for col_idx, value in enumerate(row_data):
                if isinstance(value, float):
                    item = QTableWidgetItem(f"{value:.6f}")
                else:
                    item = QTableWidgetItem(str(value))
                self.tableRoute.setItem(row_idx, col_idx, item)

        self.tableRoute.resizeColumnsToContents()

    def _on_departure_changed(self, value):
        self.state["departure_time"] = value.toString("yyyy-MM-dd HH:mm")
        self._update_summary()

    def _on_arrival_changed(self, value):
        self.state["arrival_time"] = value.toString("yyyy-MM-dd HH:mm")
        self._update_summary()

    def _on_forecast_horizon_changed(self, value):
        self.state["forecast_horizon"] = value
        self._update_summary()

    def _on_forecast_resolution_changed(self, value):
        self.state["forecast_resolution"] = value
        self._update_summary()

    def _on_algorithm_changed(self, text):
        if text == "Isofuel Algorithm":
            self.state["algorithm"] = "isofuel"
        else:
            self.state["algorithm"] = "genetic"
        self._update_summary()

    def _on_vessel_changed(self, text):
        self.state["boat_preset"] = text
        self._update_summary()

    def _on_data_mode_changed(self, text):
        self.state["data_mode"] = text
        self._update_summary()

    def _on_weather_path_changed(self, text):
        self.state["weather_path"] = text
        self._update_summary()

    def _on_depth_path_changed(self, text):
        self.state["depth_path"] = text
        self._update_summary()

    def _on_route_output_path_changed(self, text):
        self.state["route_output_path"] = text
        self._update_summary()

    def _get_vessel_preset(self):
        presets = {
            "Generic Cargo": {
                "BOAT_SPEED": 12,
                "BOAT_LENGTH": 120,
                "BOAT_BREADTH": 20,
            },
            "Fast Vessel": {
                "BOAT_SPEED": 20,
                "BOAT_LENGTH": 80,
                "BOAT_BREADTH": 14,
            },
        }
        return presets.get(self.state["boat_preset"], presets["Generic Cargo"])

    def _build_summary_text(self):
        src = self.state["source"]
        dst = self.state["destination"]

        if src:
            src_text = f"[{src[0]:.6f}, {src[1]:.6f}]"
        else:
            src_text = "Not set"

        if dst:
            dst_text = f"[{dst[0]:.6f}, {dst[1]:.6f}]"
        else:
            dst_text = "Not set"

        vessel = self._get_vessel_preset()

        lines = [
            "Route",
            f"Source: {src_text}",
            f"Destination: {dst_text}",
            f"Waypoints: {len(self.state['waypoints'])}",
            "",
            "Time & Algorithm",
            f"Departure: {self.state['departure_time']}",
            f"Arrival: {self.state['arrival_time']}",
            f"Forecast Horizon: {self.state['forecast_horizon']} h",
            f"Forecast Resolution: {self.state['forecast_resolution']} h",
            f"Algorithm: {self.state['algorithm']}",
            "",
            "Vessel",
            f"Boat Preset: {self.state['boat_preset']}",
            f"Speed: {vessel['BOAT_SPEED']} knots",
            f"Length: {vessel['BOAT_LENGTH']} m",
            f"Breadth: {vessel['BOAT_BREADTH']} m",
            "",
            "Data & Output",
            f"Data Mode: {self.state['data_mode']}",
            f"Weather Path: {self.state['weather_path']}",
            f"Depth Path: {self.state['depth_path']}",
            f"Route Output Path: {self.state['route_output_path']}",
        ]

        return "\n".join(lines)

    def _update_summary(self):
        self.summaryText.setPlainText(self._build_summary_text())

    def _build_config(self):
        if not self.state["source"] or not self.state["destination"]:
            raise ValueError("Source and Destination must be selected before export.")

        vessel = self._get_vessel_preset()

        config = {
            "DEFAULT_ROUTE": [
                [self.state["source"][0], self.state["source"][1]],
                [self.state["destination"][0], self.state["destination"][1]],
            ],
            "INTERMEDIATE_WAYPOINTS": self.state["waypoints"],
            "TIME": {
                "DEPARTURE": self.state["departure_time"],
                "ARRIVAL": self.state["arrival_time"],
                "FORECAST_HORIZON_HOURS": self.state["forecast_horizon"],
                "FORECAST_RESOLUTION_HOURS": self.state["forecast_resolution"],
            },
            "ALGORITHM": self.state["algorithm"],
            "BOAT": {
                "PRESET": self.state["boat_preset"],
                "BOAT_SPEED": vessel["BOAT_SPEED"],
                "BOAT_LENGTH": vessel["BOAT_LENGTH"],
                "BOAT_BREADTH": vessel["BOAT_BREADTH"],
            },
            "DATA": {
                "MODE": self.state["data_mode"],
                "WEATHER_DATA": self.state["weather_path"],
                "DEPTH_DATA": self.state["depth_path"],
            },
            "OUTPUT": {
                "ROUTE_PATH": self.state["route_output_path"],
            },
        }

        return config

    def _export_json(self):
        try:
            config = self._build_config()
        except ValueError as e:
            QMessageBox.warning(self, "Missing Data", str(e))
            return

        path, _ = QFileDialog.getSaveFileName(
            self,
            "Save Configuration",
            "config.runtime.json",
            "JSON Files (*.json)"
        )

        if not path:
            return

        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(config, f, indent=2)

            QMessageBox.information(
                self,
                "Export Complete",
                f"Configuration saved successfully:\n{path}"
            )
        except Exception as e:
            QMessageBox.critical(
                self,
                "Export Failed",
                f"Could not save file:\n{str(e)}"
            )
    def _collect_form_data(self):
        """Read values from UI and store in self.state"""

        self.state["departure_time"] = self.dateTimeDeparture.dateTime().toString("yyyy-MM-dd HH:mm")
        self.state["arrival_time"] = self.dateTimeArrival.dateTime().toString("yyyy-MM-dd HH:mm")

        self.state["forecast_horizon"] = self.spinForecastHorizon.value()
        self.state["forecast_resolution"] = self.spinForecastResolution.value()

        algo_text = self.comboAlgorithm.currentText().lower()

        if "isofuel" in algo_text:
            self.state["algorithm"] = "isofuel"
        else:
            self.state["algorithm"] = "genetic"

        self.state["boat_preset"] = self.comboVessel.currentText()
        self.state["data_mode"] = self.comboDataMode.currentText()

        self.state["weather_path"] = self.lineWeatherPath.text()
        self.state["depth_path"] = self.lineDepthPath.text()
        self.state["route_output_path"] = self.lineRouteOutputPath.text()
