# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WRTPluginLiteDialog
                                 A QGIS plugin
 Description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Muhammad Ahmad
        email                : mahmada2904@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QDateTime, Qt
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox, QTableWidgetItem
from qgis.utils import iface

from .route_visualiser import RouteVisualiser
from .route_map_tool import RouteMapTool
from .weather_visualiser import WeatherVisualiser

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "wrt_plugin_lite_dialog_base.ui")
)


class WRTPluginLiteDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(WRTPluginLiteDialog, self).__init__(parent)
        self.setupUi(self)

        self.state = {
            "source": None,
            "destination": None,
            "waypoints": [],
            "departure_time": None,
            "arrival_time": None,
            "use_arrival_time": False,
            "forecast_horizon": 90,
            "forecast_resolution": 3,
            "algorithm": "genetic",
            "boat_preset": "Generic Cargo",
            "data_mode": "automatic",
            "weather_path": "",
            "depth_path": "",
            "courses_path": "",
            "route_output_path": "",
        }

        self._prev_map_tool = None
        self._route_tool = RouteMapTool(iface.mapCanvas(), self._on_point_picked)

        self._setup_ui()
        self._connect_signals()
        self._load_defaults()
        self._refresh_route_table()
        self._update_navigation_buttons()
        self._update_data_mode_ui()
        self._update_summary()

    # ----------------------------
    # UI setup
    # ----------------------------
    def _setup_ui(self):
        self.navList.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)

        self.tableRoute.setHorizontalHeaderLabels(["Type", "Latitude", "Longitude"])
        self.tableRoute.verticalHeader().setVisible(False)
        self.tableRoute.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRoute.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableRoute.horizontalHeader().setStretchLastSection(True)

        now_local = QDateTime.currentDateTime()
        self.dateTimeDeparture.setDateTime(now_local)
        self.dateTimeArrival.setDateTime(now_local.addSecs(24 * 3600))

    def _connect_signals(self):
        self.navList.currentRowChanged.connect(self._change_page)
        self.btnLoadRoute.clicked.connect(self._load_route_to_qgis)
        self.btnLoadWeather.clicked.connect(self._load_weather_layer)

        self.btnNext.clicked.connect(self._go_next)
        self.btnBack.clicked.connect(self._go_back)
        self.btnCancel.clicked.connect(self.reject)

        self.btnPickRoute.clicked.connect(self._start_pick_route)
        self.btnClearRoute.clicked.connect(self._clear_route)

        self.comboAlgorithm.currentTextChanged.connect(self._on_algorithm_changed)
        self.comboVessel.currentTextChanged.connect(self._on_vessel_changed)
        self.comboDataMode.currentTextChanged.connect(self._on_data_mode_changed)

        self.checkUseArrivalTime.toggled.connect(self._on_use_arrival_time_changed)

        self.dateTimeDeparture.dateTimeChanged.connect(self._on_departure_changed)
        self.dateTimeArrival.dateTimeChanged.connect(self._on_arrival_changed)
        self.spinForecastHorizon.valueChanged.connect(self._on_forecast_horizon_changed)
        self.spinForecastResolution.valueChanged.connect(self._on_forecast_resolution_changed)

        self.lineWeatherPath.textChanged.connect(self._on_weather_path_changed)
        self.lineDepthPath.textChanged.connect(self._on_depth_path_changed)
        self.lineCoursesPath.textChanged.connect(self._on_courses_path_changed)
        self.lineRouteOutputPath.textChanged.connect(self._on_route_output_path_changed)

        self.btnBrowseWeather.clicked.connect(self._browse_weather_path)
        self.btnBrowseDepth.clicked.connect(self._browse_depth_path)
        self.btnBrowseCourses.clicked.connect(self._browse_courses_file)
        self.btnBrowseOutputDir.clicked.connect(self._browse_output_dir)

    def _load_defaults(self):
        self.comboAlgorithm.clear()
        self.comboAlgorithm.addItems([
            "Genetic Algorithm",
            "Isofuel Algorithm",
        ])

        self.comboVessel.clear()
        self.comboVessel.addItems([
            "Generic Cargo",
            "Fast Vessel",
        ])

        self.comboDataMode.clear()
        self.comboDataMode.addItems([
            "Automatic",
            "Manual",
        ])

        self.comboAlgorithm.setCurrentIndex(0)
        self.comboVessel.setCurrentText("Generic Cargo")
        self.comboDataMode.setCurrentText("Automatic")
        self.checkUseArrivalTime.setChecked(False)

        self.spinForecastHorizon.setValue(90)
        self.spinForecastResolution.setValue(3)

        # Safe defaults:
        # - in automatic mode these are output/intermediate file targets
        # - in manual mode user should browse actual existing files where applicable
        self.lineWeatherPath.setText("weather_data.nc")
        self.lineDepthPath.setText("depth_data.nc")
        self.lineCoursesPath.setText("courses.nc")
        self.lineRouteOutputPath.setText("")

        self._collect_form_data()

    # ----------------------------
    # Navigation
    # ----------------------------
    def _change_page(self, index):
        if index < 0 or index >= self.stackedWidget.count():
            return
        self.stackedWidget.setCurrentIndex(index)
        self._update_navigation_buttons()
        self._update_summary()

    def _go_next(self):
        self._collect_form_data()

        current_index = self.stackedWidget.currentIndex()
        last_index = self.stackedWidget.count() - 1

        if current_index == last_index:
            self._export_json()
            return

        next_index = current_index + 1
        self.stackedWidget.setCurrentIndex(next_index)
        self.navList.setCurrentRow(next_index)
        self._update_navigation_buttons()

        if next_index == last_index:
            self._update_summary()

    def _go_back(self):
        current = self.stackedWidget.currentIndex()
        if current > 0:
            previous = current - 1
            self.stackedWidget.setCurrentIndex(previous)
            self.navList.setCurrentRow(previous)
            self._update_navigation_buttons()

    def _update_navigation_buttons(self):
        current = self.stackedWidget.currentIndex()
        last_index = self.stackedWidget.count() - 1

        self.btnBack.setEnabled(current > 0)
        self.btnNext.setText("Finish" if current == last_index else "Next")

    # ----------------------------
    # Route picking
    # ----------------------------
    def _start_pick_route(self):
        canvas = iface.mapCanvas()
        self._prev_map_tool = canvas.mapTool()
        self._route_tool.reset()
        canvas.setMapTool(self._route_tool)

        QMessageBox.information(
            self,
            "Route Selection",
            "Click once on the map to set SOURCE, then click again to set DESTINATION."
        )

    def _on_point_picked(self, kind, lat, lon):
        if kind == "source":
            self.state["source"] = (lat, lon)
        elif kind == "destination":
            self.state["destination"] = (lat, lon)
            self._restore_previous_map_tool()

        self._refresh_route_table()
        self._update_summary()

    def _restore_previous_map_tool(self):
        canvas = iface.mapCanvas()
        if self._prev_map_tool is not None:
            canvas.setMapTool(self._prev_map_tool)
            self._prev_map_tool = None

    def _clear_route(self):
        self.state["source"] = None
        self.state["destination"] = None
        self.state["waypoints"] = []
        self._refresh_route_table()
        self._restore_previous_map_tool()
        self._update_summary()

    def _refresh_route_table(self):
        rows = []

        if self.state["source"] is not None:
            rows.append(("Source", self.state["source"][0], self.state["source"][1]))

        for i, wp in enumerate(self.state["waypoints"], start=1):
            rows.append((f"Waypoint {i}", wp[0], wp[1]))

        if self.state["destination"] is not None:
            rows.append(("Destination", self.state["destination"][0], self.state["destination"][1]))

        if not rows:
            rows = [
                ("Source", "", ""),
                ("Destination", "", "")
            ]

        self.tableRoute.setRowCount(len(rows))

        for row_idx, row_data in enumerate(rows):
            for col_idx, value in enumerate(row_data):
                if isinstance(value, float):
                    item = QTableWidgetItem(f"{value:.6f}")
                else:
                    item = QTableWidgetItem(str(value))
                item.setTextAlignment(Qt.AlignCenter)
                self.tableRoute.setItem(row_idx, col_idx, item)

        self.tableRoute.resizeColumnsToContents()

    # ----------------------------
    # State updates
    # ----------------------------
    def _on_departure_changed(self, value):
        self.state["departure_time"] = value.toUTC().toString("yyyy-MM-ddTHH:mm'Z'")
        self._update_summary()

    def _on_arrival_changed(self, value):
        self.state["arrival_time"] = value.toUTC().toString("yyyy-MM-ddTHH:mm'Z'")
        self._update_summary()

    def _on_forecast_horizon_changed(self, value):
        self.state["forecast_horizon"] = value
        self._update_summary()

    def _on_forecast_resolution_changed(self, value):
        self.state["forecast_resolution"] = value
        self._update_summary()

    def _on_algorithm_changed(self, text):
        self.state["algorithm"] = "isofuel" if "isofuel" in text.lower() else "genetic"
        self._update_summary()

    def _on_vessel_changed(self, text):
        self.state["boat_preset"] = text.strip()
        self._update_summary()

    def _on_data_mode_changed(self, text):
        self.state["data_mode"] = text.strip().lower()
        self._update_data_mode_ui()
        self._update_summary()

    def _on_use_arrival_time_changed(self, checked):
        self.state["use_arrival_time"] = checked
        self.dateTimeArrival.setEnabled(checked)
        self.labelArrivalTime.setEnabled(checked)
        self._update_summary()

    def _on_weather_path_changed(self, text):
        self.state["weather_path"] = text.strip()
        self._update_summary()

    def _on_depth_path_changed(self, text):
        self.state["depth_path"] = text.strip()
        self._update_summary()

    def _on_courses_path_changed(self, text):
        self.state["courses_path"] = text.strip()
        self._update_summary()

    def _on_route_output_path_changed(self, text):
        self.state["route_output_path"] = text.strip()
        self._update_summary()

    def _update_data_mode_ui(self):
        automatic = self.comboDataMode.currentText().strip().lower() == "automatic"

        if automatic:
            self.labelWeatherPath.setText("Weather Output File")
            self.labelDepthPath.setText("Depth Output File")
            self.labelCoursesPath.setText("Courses Output File")

            self.lineWeatherPath.setPlaceholderText("e.g. weather_data.nc or C:/wrt/data/weather_data.nc")
            self.lineDepthPath.setPlaceholderText("e.g. depth_data.nc or C:/wrt/data/depth_data.nc")
            self.lineCoursesPath.setPlaceholderText("e.g. courses.nc or C:/wrt/data/courses.nc")
        else:
            self.labelWeatherPath.setText("Weather Data File")
            self.labelDepthPath.setText("Depth Data File")
            self.labelCoursesPath.setText("Courses File")

            self.lineWeatherPath.setPlaceholderText("Select an existing weather .nc file")
            self.lineDepthPath.setPlaceholderText("Select an existing depth .nc file")
            self.lineCoursesPath.setPlaceholderText("Select or enter courses .nc file path")

        self.labelRouteOutputPath.setText("Output Directory")
        self.lineRouteOutputPath.setPlaceholderText("Select an existing folder (WRT ROUTE_PATH)")

    # ----------------------------
    # Browse helpers
    # ----------------------------
    def _browse_weather_path(self):
        automatic = self.state["data_mode"] == "automatic"

        if automatic:
            path, _ = QFileDialog.getSaveFileName(
                self,
                "Select Weather Output File",
                self.lineWeatherPath.text() or "weather_data.nc",
                "NetCDF Files (*.nc);;All Files (*)"
            )
        else:
            path, _ = QFileDialog.getOpenFileName(
                self,
                "Select Weather Data File",
                self.lineWeatherPath.text(),
                "NetCDF Files (*.nc);;All Files (*)"
            )

        if path:
            self.lineWeatherPath.setText(path)

    def _browse_depth_path(self):
        automatic = self.state["data_mode"] == "automatic"

        if automatic:
            path, _ = QFileDialog.getSaveFileName(
                self,
                "Select Depth Output File",
                self.lineDepthPath.text() or "depth_data.nc",
                "NetCDF Files (*.nc);;All Files (*)"
            )
        else:
            path, _ = QFileDialog.getOpenFileName(
                self,
                "Select Depth Data File",
                self.lineDepthPath.text(),
                "NetCDF Files (*.nc);;All Files (*)"
            )

        if path:
            self.lineDepthPath.setText(path)

    def _browse_courses_file(self):
        path, _ = QFileDialog.getSaveFileName(
            self,
            "Select Courses File",
            self.lineCoursesPath.text().strip() or "courses.nc",
            "NetCDF Files (*.nc);;All Files (*)"
        )
        if path:
            self.lineCoursesPath.setText(path)

    def _browse_output_dir(self):
        path = QFileDialog.getExistingDirectory(
            self,
            "Select Output Directory",
            self.lineRouteOutputPath.text() or ""
        )
        if path:
            self.lineRouteOutputPath.setText(path)

    # ----------------------------
    # Vessel presets
    # ----------------------------
    def _get_vessel_preset(self):
        preset = self.state["boat_preset"].strip().lower()

        if preset == "fast vessel":
            return {
                "BOAT_TYPE": "direct_power_method",
                "BOAT_SPEED": 8.0,   # m/s
                "BOAT_DRAUGHT_AFT": 8,
                "BOAT_DRAUGHT_FORE": 8,
                "BOAT_BREADTH": 24,
                "BOAT_FUEL_RATE": 180,
                "BOAT_HBR": 25,
                "BOAT_LENGTH": 140,
                "BOAT_SMCR_POWER": 7000,
                "BOAT_SMCR_SPEED": 8.0,
            }

        return {
            "BOAT_TYPE": "direct_power_method",
            "BOAT_SPEED": 6.0,   # m/s
            "BOAT_DRAUGHT_AFT": 10,
            "BOAT_DRAUGHT_FORE": 10,
            "BOAT_BREADTH": 32,
            "BOAT_FUEL_RATE": 167,
            "BOAT_HBR": 30,
            "BOAT_LENGTH": 180,
            "BOAT_SMCR_POWER": 6502,
            "BOAT_SMCR_SPEED": 6.0,
        }

    # ----------------------------
    # Summary
    # ----------------------------
    def _build_summary_text(self):
        src = self.state["source"]
        dst = self.state["destination"]

        src_text = f"[{src[0]:.6f}, {src[1]:.6f}]" if src else "Not set"
        dst_text = f"[{dst[0]:.6f}, {dst[1]:.6f}]" if dst else "Not set"

        vessel = self._get_vessel_preset()
        use_arrival = self.checkUseArrivalTime.isChecked()

        lines = [
            "Route",
            f"Source: {src_text}",
            f"Destination: {dst_text}",
            f"Waypoints: {len(self.state['waypoints'])}",
            "",
            "Time & Routing",
            f"Departure: {self.state['departure_time']}",
            f"Use Arrival Time: {'Yes' if use_arrival else 'No'}",
            f"Arrival: {self.state['arrival_time'] if use_arrival else 'Not exported'}",
            f"Forecast Horizon: {self.state['forecast_horizon']} h",
            f"Forecast Resolution: {self.state['forecast_resolution']} h",
            f"Algorithm: {self.state['algorithm']}",
            "",
            "Vessel",
            f"Boat Preset: {self.state['boat_preset']}",
            f"Boat Type: {vessel['BOAT_TYPE']}",
            f"Speed: {vessel['BOAT_SPEED']} m/s" if not use_arrival else "Speed: Not exported (arrival mode)",
            f"Length: {vessel['BOAT_LENGTH']} m",
            f"Breadth: {vessel['BOAT_BREADTH']} m",
            "",
            "Data & Output",
            f"Data Mode: {self.state['data_mode']}",
            f"Weather Path: {self._resolve_weather_path()}",
            f"Depth Path: {self._resolve_depth_path()}",
            f"Courses Path: {self._resolve_courses_path()}",
            f"Output Directory (ROUTE_PATH): {self.state['route_output_path'] or 'Not set'}",
        ]

        if self.state["data_mode"] == "automatic":
            lines.extend([
                "",
                "Note",
                "Automatic mode requires CMEMS credentials on the machine running WRT.",
            ])

        return "\n".join(lines)

    def _update_summary(self):
        self.summaryText.setPlainText(self._build_summary_text())

    # ----------------------------
    # Data collection / validation
    # ----------------------------
    def _collect_form_data(self):
        self.state["departure_time"] = self.dateTimeDeparture.dateTime().toUTC().toString("yyyy-MM-ddTHH:mm'Z'")
        self.state["arrival_time"] = self.dateTimeArrival.dateTime().toUTC().toString("yyyy-MM-ddTHH:mm'Z'")
        self.state["use_arrival_time"] = self.checkUseArrivalTime.isChecked()

        self.state["forecast_horizon"] = self.spinForecastHorizon.value()
        self.state["forecast_resolution"] = self.spinForecastResolution.value()

        algo_text = self.comboAlgorithm.currentText().strip().lower()
        self.state["algorithm"] = "isofuel" if "isofuel" in algo_text else "genetic"

        self.state["boat_preset"] = self.comboVessel.currentText().strip()
        self.state["data_mode"] = self.comboDataMode.currentText().strip().lower()

        self.state["weather_path"] = self.lineWeatherPath.text().strip()
        self.state["depth_path"] = self.lineDepthPath.text().strip()
        self.state["courses_path"] = self.lineCoursesPath.text().strip()
        self.state["route_output_path"] = self.lineRouteOutputPath.text().strip()

    def _resolve_weather_path(self):
        path = self.state["weather_path"].strip()
        output_dir = self.state["route_output_path"].strip()

        if path:
            return path

        if output_dir:
            return os.path.join(output_dir, "weather_data.nc").replace("\\", "/")

        return "weather_data.nc"

    def _resolve_depth_path(self):
        path = self.state["depth_path"].strip()
        output_dir = self.state["route_output_path"].strip()

        if path:
            return path

        if output_dir:
            return os.path.join(output_dir, "depth_data.nc").replace("\\", "/")

        return "depth_data.nc"

    def _resolve_courses_path(self):
        path = self.state["courses_path"].strip()
        output_dir = self.state["route_output_path"].strip()

        if path:
            return path

        if output_dir:
            return os.path.join(output_dir, "courses.nc").replace("\\", "/")

        return "courses.nc"

    def _validate_before_export(self):
        errors = []

        if not self.state["source"]:
            errors.append("Source is not set.")

        if not self.state["destination"]:
            errors.append("Destination is not set.")

        output_dir = self.state["route_output_path"].strip()
        if not output_dir:
            errors.append("Output Directory is required.")
        elif not os.path.isdir(output_dir):
            errors.append("Output Directory must be an existing folder.")

        if self.state["use_arrival_time"]:
            dep = self.dateTimeDeparture.dateTime().toSecsSinceEpoch()
            arr = self.dateTimeArrival.dateTime().toSecsSinceEpoch()
            if arr <= dep:
                errors.append("Arrival Time must be later than Departure Time.")

        if self.state["data_mode"] == "manual":
            weather_path = self._resolve_weather_path()
            depth_path = self._resolve_depth_path()
            courses_path = self._resolve_courses_path()

            if not weather_path:
                errors.append("Weather Data File is required in Manual mode.")
            elif not os.path.isfile(weather_path):
                errors.append("Weather Data File must exist in Manual mode.")

            if not depth_path:
                errors.append("Depth Data File is required in Manual mode.")
            elif not os.path.isfile(depth_path):
                errors.append("Depth Data File must exist in Manual mode.")

            if self.state["algorithm"] == "genetic":
                if not courses_path:
                    errors.append("Courses File is required for Genetic mode.")
                else:
                    courses_dir = os.path.dirname(courses_path) or "."
                    if not os.path.isdir(courses_dir):
                        errors.append("Courses File folder must exist.")

        if errors:
            raise ValueError("\n".join(errors))

    # ----------------------------
    # Config building
    # ----------------------------
    def _build_config(self):
        self._validate_before_export()

        vessel = self._get_vessel_preset()

        source = self.state["source"]
        destination = self.state["destination"]
        waypoints = self.state["waypoints"] or []

        default_route = [
            float(source[0]),
            float(source[1]),
            float(destination[0]),
            float(destination[1]),
        ]

        all_points = [source] + waypoints + [destination]
        lats = [float(p[0]) for p in all_points]
        lons = [float(p[1]) for p in all_points]
        default_map = [
            min(lats),
            min(lons),
            max(lats),
            max(lons),
        ]

        intermediate_waypoints = [
            [float(p[0]), float(p[1])] for p in waypoints
        ]

        config = {
            "DEFAULT_MAP": default_map,
            "DEFAULT_ROUTE": default_route,
            "DEPARTURE_TIME": self.state["departure_time"],
            "ROUTE_PATH": self.state["route_output_path"].replace("\\", "/"),

            "BOAT_BREADTH": vessel["BOAT_BREADTH"],
            "BOAT_FUEL_RATE": vessel["BOAT_FUEL_RATE"],
            "BOAT_HBR": vessel["BOAT_HBR"],
            "BOAT_LENGTH": vessel["BOAT_LENGTH"],
            "BOAT_SMCR_POWER": vessel["BOAT_SMCR_POWER"],
            "BOAT_SMCR_SPEED": vessel["BOAT_SMCR_SPEED"],
            "BOAT_TYPE": vessel["BOAT_TYPE"],
            "BOAT_DRAUGHT_AFT": vessel["BOAT_DRAUGHT_AFT"],
            "BOAT_DRAUGHT_FORE": vessel["BOAT_DRAUGHT_FORE"],

            "INTERMEDIATE_WAYPOINTS": intermediate_waypoints,
            "ALGORITHM_TYPE": self.state["algorithm"],
            "DATA_MODE": self.state["data_mode"],

            "TIME_FORECAST": self.state["forecast_horizon"],
            "DELTA_TIME_FORECAST": self.state["forecast_resolution"],

            "CONSTRAINTS_LIST": [
                "land_crossing_global_land_mask",
                "water_depth",
                "on_map"
            ],

            "DELTA_FUEL": 3000,
            "ROUTER_HDGS_SEGMENTS": 30,
            "ROUTER_HDGS_INCREMENTS_DEG": 6,
            "ISOCHRONE_PRUNE_SECTOR_DEG_HALF": 91,
            "ISOCHRONE_PRUNE_SEGMENTS": 20,
            "ISOCHRONE_MINIMISATION_CRITERION": "squareddist_over_disttodest",
            "ISOCHRONE_NUMBER_OF_ROUTES": 1,

            "GENETIC_NUMBER_GENERATIONS": 20,
            "GENETIC_NUMBER_OFFSPRINGS": 2,
            "GENETIC_POPULATION_SIZE": 20,
            "GENETIC_POPULATION_TYPE": "isofuel",
            "GENETIC_REPAIR_TYPE": [
                "waypoints_infill",
                "constraint_violation"
            ],
            "GENETIC_MUTATION_TYPE": "random",
            "GENETIC_CROSSOVER_TYPE": "random",
            "GENETIC_CROSSOVER_PATCHER": "isofuel",
            "GENETIC_FIX_RANDOM_SEED": False,
        }

        # File-based fields
        if self.state["data_mode"] == "manual":
            config["WEATHER_DATA"] = self._resolve_weather_path()
            config["DEPTH_DATA"] = self._resolve_depth_path()
            config["COURSES_FILE"] = self._resolve_courses_path()
        else:
            weather_path = self._resolve_weather_path()
            depth_path = self._resolve_depth_path()
            courses_path = self._resolve_courses_path()

            if weather_path:
                config["WEATHER_DATA"] = weather_path
            if depth_path:
                config["DEPTH_DATA"] = depth_path
            if courses_path:
                config["COURSES_FILE"] = courses_path

        # WRT validation in your install rejects BOAT_SPEED + ARRIVAL_TIME together.
        if self.state["use_arrival_time"]:
            config["ARRIVAL_TIME"] = self.state["arrival_time"]
        else:
            config["BOAT_SPEED"] = vessel["BOAT_SPEED"]

        return config

    # ----------------------------
    # Export
    # ----------------------------
    def _export_json(self):
        self._collect_form_data()

        try:
            config = self._build_config()
        except ValueError as e:
            QMessageBox.warning(self, "Validation Error", str(e))
            return

        path, _ = QFileDialog.getSaveFileName(
            self,
            "Save Configuration",
            "config.runtime.json",
            "JSON Files (*.json)"
        )

        if not path:
            return

        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(config, f, indent=2)

            QMessageBox.information(
                self,
                "Export Complete",
                f"Configuration saved successfully:\n{path}"
            )
            self.accept()

        except Exception as e:
            QMessageBox.critical(
                self,
                "Export Failed",
                f"Could not save file:\n{str(e)}"
            )
    
    def _load_route_to_qgis(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Load WRT Route",
            "",
            "JSON Files (*.json);;All Files (*)"
        )
        if not path:
            return

        rv = RouteVisualiser()
        line_layer, point_layer = rv.load_route(path)

        if point_layer is None:
            QMessageBox.warning(self, "Load Failed",
                "Could not load route. Check the file is a valid WRT output JSON.")
            return

        summary = rv.get_route_summary(point_layer)
        lines = []
        lines.append(f"Loaded {summary.get('waypoints', '?')} waypoints")
        if summary.get("speed_mean"):
            lines.append(
                f"Speed: {summary['speed_min']} - "
                f"{summary['speed_max']} m/s  "
                f"(avg {summary['speed_mean']} m/s)"
            )
        if summary.get("fuel_total"):
            lines.append(f"Total fuel: {summary['fuel_total']} t/h")
        if summary.get("engine_power_mean"):
            lines.append(f"Avg engine power: {summary['engine_power_mean']} kW")

        self.labelRouteSummary.setText("\n".join(lines))
    def _load_weather_layer(self):
        # Step 1 — pick the NetCDF file
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Load Weather Data",
            "",
            "NetCDF Files (*.nc);;All Files (*)"
        )
        if not path:
            return

        # Step 2 — populate variable combo
        wv = WeatherVisualiser()
        variables = wv.get_available_variables(path)

        if not variables:
            QMessageBox.warning(
                self,
                "No Variables Found",
                "Could not read any known variables from this file."
            )
            return

        self.comboWeatherVariable.clear()
        for var_name, label, unit in variables:
            self.comboWeatherVariable.addItem(
                f"{label} ({unit})", userData=var_name
            )

        # Step 3 — load the selected variable at time step 0
        var_name = self.comboWeatherVariable.currentData()
        layer = wv.load_variable(path, var_name, time_index=0)

        if layer is None:
            QMessageBox.warning(
                self,
                "Load Failed",
                f"Could not load variable '{var_name}' from file."
            )
            return

        # Step 4 — compute stats for current map extent
        canvas_extent = iface.mapCanvas().extent()
        stats = wv.compute_bbox_stats(path, var_name, 0, canvas_extent)

        if stats:
            self.labelWeatherStats.setText(
                f"mean: {stats['mean']} {stats['unit']}  "
                f"min: {stats['min']}  max: {stats['max']}"
            )
        else:
            self.labelWeatherStats.setText("Layer loaded")

        # Store path for combo changes
        self._weather_nc_path = path
        self._weather_visualiser = wv

        # Connect combo change to reload
        try:
            self.comboWeatherVariable.currentIndexChanged.disconnect(
                self._on_weather_variable_changed
            )
        except Exception:
            pass
        self.comboWeatherVariable.currentIndexChanged.connect(
            self._on_weather_variable_changed
        )

    def _on_weather_variable_changed(self, index):
        """Reload layer when user picks a different variable."""
        if not hasattr(self, "_weather_nc_path"):
            return

        var_name = self.comboWeatherVariable.currentData()
        if not var_name:
            return

        layer = self._weather_visualiser.load_variable(
            self._weather_nc_path, var_name, time_index=0
        )

        if layer:
            canvas_extent = iface.mapCanvas().extent()
            stats = self._weather_visualiser.compute_bbox_stats(
                self._weather_nc_path, var_name, 0, canvas_extent
            )
            if stats:
                self.labelWeatherStats.setText(
                    f"mean: {stats['mean']} {stats['unit']}  "
                    f"min: {stats['min']}  max: {stats['max']}"
                )